/**
 * @file io_quic.h
 * @brief QUIC transport — ngtcp2-backed, buffer-based I/O.
 *
 * No socket I/O — application feeds UDP datagrams via io_quic_on_recv(),
 * retrieves output datagrams via io_quic_flush(). Timer-driven via
 * io_quic_timeout(). Same buffer pattern as io_http2.
 */

#ifndef IOHTTP_HTTP_QUIC_H
#define IOHTTP_HTTP_QUIC_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
#include <netinet/in.h>

/* ---- Forward declaration (opaque) ---- */

typedef struct io_quic_conn io_quic_conn_t;

/* ---- Configuration ---- */

typedef struct {
    uint32_t max_streams_bidi;      /* default 100 */
    uint32_t max_stream_data_bidi;  /* per-stream flow control, default 256 KiB */
    uint32_t max_data;              /* connection-level flow control, default 1 MiB */
    uint32_t idle_timeout_ms;       /* default 30000 */
    uint32_t max_udp_payload;       /* default 1200 (initial), grows after handshake */
    const char *cert_file;          /* TLS certificate */
    const char *key_file;           /* TLS private key */
} io_quic_config_t;

/* ---- Callback types ---- */

/**
 * @brief Called when stream data is received from the peer.
 * @param conn      QUIC connection.
 * @param stream_id QUIC stream ID (client-initiated bidi: 0, 4, 8, ...).
 * @param data      Stream data bytes.
 * @param len       Number of bytes.
 * @param fin       true if this is the final data on this stream.
 * @param user_data User context from io_quic_conn_create().
 * @return 0 on success, negative errno on failure.
 */
typedef int (*io_quic_stream_data_fn)(io_quic_conn_t *conn, int64_t stream_id,
                                       const uint8_t *data, size_t len,
                                       bool fin, void *user_data);

/**
 * @brief Called when a new stream is opened by the peer.
 * @param conn      QUIC connection.
 * @param stream_id New stream ID.
 * @param user_data User context.
 * @return 0 on success, negative errno to reject.
 */
typedef int (*io_quic_stream_open_fn)(io_quic_conn_t *conn, int64_t stream_id,
                                       void *user_data);

/**
 * @brief Called when the QUIC handshake completes.
 * @param conn      QUIC connection.
 * @param user_data User context.
 */
typedef void (*io_quic_handshake_done_fn)(io_quic_conn_t *conn, void *user_data);

typedef struct {
    io_quic_stream_data_fn on_stream_data;
    io_quic_stream_open_fn on_stream_open;
    io_quic_handshake_done_fn on_handshake_done;
} io_quic_callbacks_t;

/* ---- Connection lifecycle ---- */

/**
 * @brief Initialize config with safe defaults.
 */
void io_quic_config_init(io_quic_config_t *cfg);

/**
 * @brief Validate a QUIC configuration.
 * @return 0 on success, negative errno on error.
 */
[[nodiscard]] int io_quic_config_validate(const io_quic_config_t *cfg);

/**
 * @brief Create a QUIC server connection from an Initial packet.
 * @param cfg       Configuration.
 * @param cbs       Callbacks for stream events.
 * @param dcid      Destination Connection ID from Initial packet.
 * @param dcid_len  DCID length.
 * @param scid      Source Connection ID (generated by server).
 * @param scid_len  SCID length.
 * @param local     Local address (server).
 * @param remote    Remote address (client).
 * @param user_data Passed to callbacks.
 * @return New connection, or nullptr on failure.
 */
[[nodiscard]] io_quic_conn_t *io_quic_conn_create(const io_quic_config_t *cfg,
                                                    const io_quic_callbacks_t *cbs,
                                                    const uint8_t *dcid, size_t dcid_len,
                                                    const uint8_t *scid, size_t scid_len,
                                                    const struct sockaddr *local,
                                                    const struct sockaddr *remote,
                                                    void *user_data);

/**
 * @brief Destroy a QUIC connection and free all resources.
 */
void io_quic_conn_destroy(io_quic_conn_t *conn);

/* ---- Data processing ---- */

/**
 * @brief Feed a received UDP datagram into the QUIC connection.
 * @param conn   Connection.
 * @param data   Raw UDP payload.
 * @param len    Payload length.
 * @param remote Sender address.
 * @return 0 on success, negative errno on error.
 */
[[nodiscard]] int io_quic_on_recv(io_quic_conn_t *conn, const uint8_t *data, size_t len,
                                   const struct sockaddr *remote);

/**
 * @brief Get pending output datagrams to send.
 * @param conn     Connection.
 * @param out_data Set to output buffer (valid until next flush/recv/timeout).
 * @param out_len  Set to output length.
 * @return 0 on success (may set out_len=0), negative errno on error.
 */
[[nodiscard]] int io_quic_flush(io_quic_conn_t *conn, const uint8_t **out_data,
                                 size_t *out_len);

/**
 * @brief Handle timer expiration (retransmission, loss detection).
 * Must be called when io_quic_get_timeout() expires.
 * @return 0 on success, negative errno on error.
 */
[[nodiscard]] int io_quic_on_timeout(io_quic_conn_t *conn);

/**
 * @brief Write data to a QUIC stream.
 * @param conn      Connection.
 * @param stream_id Stream to write to.
 * @param data      Data to send.
 * @param len       Data length.
 * @param fin       true to close the stream after this write.
 * @return Bytes written (>= 0), negative errno on error.
 */
[[nodiscard]] ssize_t io_quic_write_stream(io_quic_conn_t *conn, int64_t stream_id,
                                            const uint8_t *data, size_t len, bool fin);

/* ---- State queries ---- */

/** @return Timeout in milliseconds until next timer event, or UINT64_MAX if none. */
[[nodiscard]] uint64_t io_quic_get_timeout(const io_quic_conn_t *conn);

/** @return true if the handshake is complete. */
[[nodiscard]] bool io_quic_is_handshake_done(const io_quic_conn_t *conn);

/** @return true if the connection is closed or draining. */
[[nodiscard]] bool io_quic_is_closed(const io_quic_conn_t *conn);

/** @return true if there is data to flush. */
[[nodiscard]] bool io_quic_want_write(const io_quic_conn_t *conn);

/**
 * @brief Initiate graceful QUIC connection close.
 * @param conn       Connection.
 * @param error_code Application error code (0 = no error).
 * @return 0 on success, negative errno on error.
 */
[[nodiscard]] int io_quic_close(io_quic_conn_t *conn, uint64_t error_code);

#endif /* IOHTTP_HTTP_QUIC_H */
