/**
 * @file ioh_quic.h
 * @brief QUIC transport — ngtcp2-backed, buffer-based I/O.
 *
 * No socket I/O — application feeds UDP datagrams via ioh_quic_on_recv(),
 * retrieves output datagrams via ioh_quic_flush(). Timer-driven via
 * ioh_quic_timeout(). Same buffer pattern as ioh_http2.
 */

#ifndef IOHTTP_HTTP_QUIC_H
#define IOHTTP_HTTP_QUIC_H

#include <netinet/in.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>

/* ---- Forward declaration (opaque) ---- */

typedef struct ioh_quic_conn ioh_quic_conn_t;

/* ---- Configuration ---- */

typedef struct {
    uint32_t max_streams_bidi;     /* default 100 */
    uint32_t max_stream_data_bidi; /* per-stream flow control, default 256 KiB */
    uint32_t max_data;             /* connection-level flow control, default 1 MiB */
    uint32_t idle_timeout_ms;      /* default 30000 */
    uint32_t max_udp_payload;      /* default 1200 (initial), grows after handshake */
    const char *cert_file;         /* TLS certificate */
    const char *key_file;          /* TLS private key */
} ioh_quic_config_t;

/* ---- Callback types ---- */

/**
 * @brief Called when stream data is received from the peer.
 * @param conn      QUIC connection.
 * @param stream_id QUIC stream ID (client-initiated bidi: 0, 4, 8, ...).
 * @param data      Stream data bytes.
 * @param len       Number of bytes.
 * @param fin       true if this is the final data on this stream.
 * @param user_data User context from ioh_quic_conn_create().
 * @return 0 on success, negative errno on failure.
 */
typedef int (*ioh_quic_stream_data_fn)(ioh_quic_conn_t *conn, int64_t stream_id, const uint8_t *data,
                                      size_t len, bool fin, void *user_data);

/**
 * @brief Called when a new stream is opened by the peer.
 * @param conn      QUIC connection.
 * @param stream_id New stream ID.
 * @param user_data User context.
 * @return 0 on success, negative errno to reject.
 */
typedef int (*ioh_quic_stream_open_fn)(ioh_quic_conn_t *conn, int64_t stream_id, void *user_data);

/**
 * @brief Called when the QUIC handshake completes.
 * @param conn      QUIC connection.
 * @param user_data User context.
 */
typedef void (*ioh_quic_handshake_done_fn)(ioh_quic_conn_t *conn, void *user_data);

typedef struct {
    ioh_quic_stream_data_fn on_stream_data;
    ioh_quic_stream_open_fn on_stream_open;
    ioh_quic_handshake_done_fn on_handshake_done;
} ioh_quic_callbacks_t;

/* ---- Connection lifecycle ---- */

/**
 * @brief Initialize config with safe defaults.
 */
void ioh_quic_config_init(ioh_quic_config_t *cfg);

/**
 * @brief Validate a QUIC configuration.
 * @return 0 on success, negative errno on error.
 */
[[nodiscard]] int ioh_quic_config_validate(const ioh_quic_config_t *cfg);

/**
 * @brief Create a QUIC server connection from an Initial packet.
 * @param cfg       Configuration.
 * @param cbs       Callbacks for stream events.
 * @param dcid      Destination Connection ID from Initial packet.
 * @param dcid_len  DCID length.
 * @param scid      Source Connection ID (generated by server).
 * @param scid_len  SCID length.
 * @param local     Local address (server).
 * @param remote    Remote address (client).
 * @param user_data Passed to callbacks.
 * @return New connection, or nullptr on failure.
 */
[[nodiscard]] ioh_quic_conn_t *
ioh_quic_conn_create(const ioh_quic_config_t *cfg, const ioh_quic_callbacks_t *cbs,
                    const uint8_t *dcid, size_t dcid_len, const uint8_t *scid, size_t scid_len,
                    const struct sockaddr *local, const struct sockaddr *remote, void *user_data);

/**
 * @brief Destroy a QUIC connection and free all resources.
 */
void ioh_quic_conn_destroy(ioh_quic_conn_t *conn);

/* ---- Data processing ---- */

/**
 * @brief Feed a received UDP datagram into the QUIC connection.
 * @param conn   Connection.
 * @param data   Raw UDP payload.
 * @param len    Payload length.
 * @param remote Sender address.
 * @return 0 on success, negative errno on error.
 */
[[nodiscard]] int ioh_quic_on_recv(ioh_quic_conn_t *conn, const uint8_t *data, size_t len,
                                  const struct sockaddr *remote);

/**
 * @brief Get pending output datagrams to send.
 * @param conn     Connection.
 * @param out_data Set to output buffer (valid until next flush/recv/timeout).
 * @param out_len  Set to output length.
 * @return 0 on success (may set out_len=0), negative errno on error.
 */
[[nodiscard]] int ioh_quic_flush(ioh_quic_conn_t *conn, const uint8_t **out_data, size_t *out_len);

/**
 * @brief Handle timer expiration (retransmission, loss detection).
 * Must be called when ioh_quic_get_timeout() expires.
 * @return 0 on success, negative errno on error.
 */
[[nodiscard]] int ioh_quic_on_timeout(ioh_quic_conn_t *conn);

/**
 * @brief Write data to a QUIC stream.
 * @param conn      Connection.
 * @param stream_id Stream to write to.
 * @param data      Data to send.
 * @param len       Data length.
 * @param fin       true to close the stream after this write.
 * @return Bytes written (>= 0), negative errno on error.
 */
[[nodiscard]] ssize_t ioh_quic_write_stream(ioh_quic_conn_t *conn, int64_t stream_id,
                                           const uint8_t *data, size_t len, bool fin);

/* ---- State queries ---- */

/** @return Timeout in milliseconds until next timer event, or UINT64_MAX if none. */
[[nodiscard]] uint64_t ioh_quic_get_timeout(const ioh_quic_conn_t *conn);

/** @return true if the handshake is complete. */
[[nodiscard]] bool ioh_quic_is_handshake_done(const ioh_quic_conn_t *conn);

/** @return true if the connection is closed or draining. */
[[nodiscard]] bool ioh_quic_is_closed(const ioh_quic_conn_t *conn);

/** @return true if there is data to flush. */
[[nodiscard]] bool ioh_quic_want_write(const ioh_quic_conn_t *conn);

/**
 * @brief Open a local unidirectional stream.
 * @param conn      Connection.
 * @param stream_id Set to the new stream ID on success.
 * @return 0 on success, negative errno on error.
 */
[[nodiscard]] int ioh_quic_open_uni_stream(ioh_quic_conn_t *conn, int64_t *stream_id);

/**
 * @brief Initiate graceful QUIC connection close.
 * @param conn       Connection.
 * @param error_code Application error code (0 = no error).
 * @return 0 on success, negative errno on error.
 */
[[nodiscard]] int ioh_quic_close(ioh_quic_conn_t *conn, uint64_t error_code);

#endif /* IOHTTP_HTTP_QUIC_H */
